version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: billingSystem
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "billingSystem"
    ports:
      - "5432:5432"

  postgres-tests:
    image: postgres:latest
    container_name: billingSystemTests
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "billingSystemTests"
    ports:
      - "5433:5432"
