version: '3.8'

services:
  postgres:
    image: postgres:12.20-alpine3.20
    container_name: billing
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "billing"
    ports:
      - "5432:5432"

  postgres-tests:
    image: postgres:12.20-alpine3.20
    container_name: billingTests
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "billingTest"
    ports:
      - "5433:5432"
