version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: billing-system
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"

#    volumes:
#      - mysql-data:/var/lib/mysql
#    networks:
#      - my_network
#
#volumes:
#  mysql-data:
#
#networks:
#  my_network:
#    driver: bridge
